#This is a makefile.
#CH-230-A
#a7_p3.[c or cpp or h]
#Shayan Khan
#skhan01@jacobs-university.de

CC = gcc
CFLAGS = -Wall

use_linked_list.o:	linked_list.h use_linked_list.c

linked_list.o:	linked_list.h linked_list.c

OBJ = linked_list.o use_linked_list.o

all:	use_linked_list

use_linked_list:	$(OBJ)
					$(CC) $(CFLAGS) -o use_linked_list $(OBJ)

run:
	./use_linked_list.c

clean:
	rm -f use_linked_list *.o	