/*
CH-230-A
a5_p8.[c or cpp or h]
Shayan Ali Khan
skhan01@jacobs-university.de
*/
/*
in the main function we read from the keyboard 
the dimensions for our matrices then we 
use duoble pointers for dynamically allocating memory
for each matrix that was passed as parameter to the 
print function
then we call all the 3 functions 
we declared for scaning 
multiplying and printing 
in the scan function we scan elements of 
both the first and second matrix
the 3 matrix is generated by multiplication function
to scan dimensions of the matrices
dynamically allocating the 3 matrices:

*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
void scan(int **first, int **second, int n, int m)
{
    int i, j;
    for (i = 0; i < n; i++){
        for (j = 0; j < n; j++){
        scanf("%d", &first[i][j]);
        }
    }
    for (i = 0; i < m; i++){
        for (j = 0; j < m; j++){
        scanf("%d", &second[i][j]);
}}
}

void multiply(int **first, int **second, int **third, int m){
    int i, j, k;
    int sum = 0;
    for (i = 0; i < m; i++){
        for (j = 0; j < m; j++){
            for (k = 0; k < m; ++k){
            sum += first[i][k] * second[k][j];
            }
            third[i][j] = sum;
            sum = 0; 
}}
}

void print(int **first, int **second, int **third, int n, int m, int p)
{
    int i, j;
    printf("Matrix A:\n");
    for (i = 0; i < n; i++){
        for (j = 0; j < n; j++){
            printf("%d ", first[i][j]);
        }
        printf("\n");
    }
    printf("Matrix B:\n");
    for (i = 0; i < n; i++){
        for (j = 0; j < n; j++){
            printf("%d ", second[i][j]);
        }
        printf("\n");
    }
    printf("The multiplication result AxB:\n");
    for (i = 0; i < m; i++){
        for (j = 0; j < m; j++){
            printf("%d ", third[i][j]);
        }
        printf("\n");
}
}
int main()
{
    int n, m, p, i;
    scanf("%d", &n);
    scanf("%d", &m);
    scanf("%d", &p);
    int **first;
    first = (int **)malloc(sizeof(int *) * n);
    for (i = 0; i < n; i++){
        first[i] = (int *)malloc(sizeof(int) * n);
    }
    int **second;
    second = (int **)malloc(sizeof(int *) * m);
    for (i = 0; i < n; i++){
        second[i] = (int *)malloc(sizeof(int) * m);
    }
    int **third;
    third = (int **)malloc(sizeof(int *) * p);
    for (i = 0; i < n; i++){
        third[i] = (int *)malloc(sizeof(int) * p);
    }
    scan(first, second, n, m);
    multiply(first, second, third, m);
    print(first, second, third, n, m, p);
    for (i = 0; i < n; i++){
        free(first[i]);
    }
    free(first);
    for (i = 0; i < m; i++){
        free(second[i]);
    }
    free(second);
    for (i = 0; i < p; i++){
        free(third[i]);
    }
    free(third);
    return 0;
}